Styling for reference generated using Autodoc
wagtail/sphinx_wagtail_theme pull request #230
Opened 2022-10-17 17:22 UTC by Temidayo32

This pull request addresses an indentation problem ( issue #228) when using `sphinx.ext.autodoc` to generate documentation automatically from the source code.

2022-10-26 20:34 UTC, lb- requested changes
@Temidayo32  this is a good start but we will have to make some tweaks to get this in.

```
dl.class {
  .sig-object + dd {
    margin: 0 0 0.5rem 1.5rem;
  }
}
```

This approach does a few things differently - it 'scopes' the styles to only the elements we care about and also uses rems for margins to ensure we nicely support different zoom & font sizes.

2022-10-26 20:36 UTC, lb- approved these changes
I will merge this in with the recommended changes for now and we can discuss more on the other PR.

Also - please let me know your preferred name for the changelog, I could not find a name on your git commit nor your GitHub profile.

2022-10-26 20:36 UTC, merged

2022-10-27 05:12 UTC, Temidayo32 commented
Thanks @lb- for the feedback. I will immediately make the changes and get back to you soonest.

2022-10-27 05:13 UTC, Temidayo32 commented
My preferred is Temidayo, or my full name of you want, Temidayo Azeez

2022-10-27 11:29 UTC, lb- commented
Changelog added 0368547e4fc18d4ea6f9d095660f05b8f784bdaf